// chicagoItinerary.js
// All the Chicago trip data, organized by day.
// Each activity has a time, title, emoji, category (for color coding),
// notes, and a "completed" flag you can toggle in the app.

const chicagoItinerary = {
  name: "Chicago April 2026",
  destination: "Chicago, IL",
  startDate: "2026-04-17",
  endDate: "2026-04-20",
  days: [
    {
      id: "fri-apr-17",
      date: "2026-04-17",
      label: "Fri 4/17",
      labelFull: "Friday, April 17",
      activities: [
        {
          id: "fri-1",
          time: "17:00",
          title: "Arrive O'Hare",
          emoji: "✈️",
          category: "travel",
          notes: "",
          address: "O'Hare International Airport, Chicago, IL",
          completed: false,
        },
        {
          id: "fri-2",
          time: "18:00",
          title: "Check In / Freshen Up",
          emoji: "🚗",
          category: "travel",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "fri-3",
          time: "19:00",
          title: "Dinner — Tuk Tuk Thai",
          emoji: "🍜",
          category: "confirmed",
          notes: "",
          address: "Tuk Tuk Thai, Chicago, IL",
          completed: false,
        },
        {
          id: "fri-4",
          time: "21:00",
          title: "Rooftop Cocktails",
          emoji: "🍸",
          category: "romantic",
          notes: "Raised at The Pendry or The Lonesome Rose",
          address: "",
          completed: false,
        },
      ],
    },
    {
      id: "sat-apr-18",
      date: "2026-04-18",
      label: "Sat 4/18",
      labelFull: "Saturday, April 18",
      activities: [
        {
          id: "sat-1",
          time: "07:00",
          title: "Architecture Boat Tour",
          emoji: "⛵",
          category: "confirmed",
          notes: "Book in advance — sells out on weekends",
          address: "Chicago Architecture Center, 111 E Wacker Dr, Chicago, IL",
          completed: false,
        },
        {
          id: "sat-2",
          time: "08:00",
          title: "Architecture Boat Tour (cont.)",
          emoji: "⛵",
          category: "confirmed",
          notes: "~90 min cruise",
          address: "",
          completed: false,
        },
        {
          id: "sat-3",
          time: "09:00",
          title: "Slow Morning / Coffee",
          emoji: "☕",
          category: "free",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "sat-4",
          time: "10:00",
          title: "Millennium Park — The Bean",
          emoji: "🫘",
          category: "new",
          notes: "",
          address: "Cloud Gate, 201 E Randolph St, Chicago, IL",
          completed: false,
        },
        {
          id: "sat-5",
          time: "11:00",
          title: "Millennium Park stroll",
          emoji: "🫘",
          category: "new",
          notes: "",
          address: "Millennium Park, Chicago, IL",
          completed: false,
        },
        {
          id: "sat-6",
          time: "12:00",
          title: "Lunch — Pequod's Deep Dish",
          emoji: "🍕",
          category: "confirmed",
          notes: "Call ahead — popular",
          address: "Pequod's Pizza, 2207 N Clybourn Ave, Chicago, IL",
          completed: false,
        },
        {
          id: "sat-7",
          time: "13:00",
          title: "Pequod's Deep Dish (cont.)",
          emoji: "🍕",
          category: "confirmed",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "sat-8",
          time: "14:00",
          title: "Lincoln Park Conservatory",
          emoji: "🌿",
          category: "orange",
          notes: "Free admission",
          address: "Lincoln Park Conservatory, 2391 N Stockton Dr, Chicago, IL",
          completed: false,
        },
        {
          id: "sat-9",
          time: "15:00",
          title: "Made in Chicago Hoodie Bar",
          emoji: "🛍️",
          category: "orange",
          notes: "17 S Wabash Ave — walk-in, open Wed–Sun 12–6 PM",
          address: "17 S Wabash Ave, Chicago, IL",
          completed: false,
        },
        {
          id: "sat-10",
          time: "16:00",
          title: "Pre-show Drinks",
          emoji: "🍸",
          category: "free",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "sat-11",
          time: "22:00",
          title: "Magic Lounge",
          emoji: "🎩",
          category: "confirmed",
          notes: "10 PM show",
          address: "Chicago Magic Lounge, 5050 N Clark St, Chicago, IL",
          completed: false,
        },
        {
          id: "sat-12",
          time: "23:00",
          title: "Magic Lounge (cont.)",
          emoji: "🎩",
          category: "confirmed",
          notes: "",
          address: "",
          completed: false,
        },
      ],
    },
    {
      id: "sun-apr-19",
      date: "2026-04-19",
      label: "Sun 4/19",
      labelFull: "Sunday, April 19",
      activities: [
        {
          id: "sun-1",
          time: "09:00",
          title: "Mr. Beef — Italian Beef Sandwich",
          emoji: "🥩",
          category: "orange",
          notes: "Casual brunch stop",
          address: "Mr. Beef, 666 N Orleans St, Chicago, IL",
          completed: false,
        },
        {
          id: "sun-2",
          time: "11:00",
          title: "McDonald's Global Menu",
          emoji: "🍟",
          category: "orange",
          notes: "1035 W. Randolph St — go early, items sell out by evening",
          address: "1035 W Randolph St, Chicago, IL",
          completed: false,
        },
        {
          id: "sun-3",
          time: "12:00",
          title: "McDonald's Global Menu (cont.)",
          emoji: "🍟",
          category: "orange",
          notes: "Check current menu on McDonald's app before going",
          address: "",
          completed: false,
        },
        {
          id: "sun-4",
          time: "13:00",
          title: "Art Institute of Chicago",
          emoji: "🏛️",
          category: "new",
          notes: "Impressionist galleries are a highlight",
          address: "Art Institute of Chicago, 111 S Michigan Ave, Chicago, IL",
          completed: false,
        },
        {
          id: "sun-5",
          time: "14:00",
          title: "Art Institute (cont.)",
          emoji: "🏛️",
          category: "new",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "sun-6",
          time: "15:00",
          title: "Art Institute (cont.)",
          emoji: "🏛️",
          category: "new",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "sun-7",
          time: "16:00",
          title: "Sluggers Batting Cages",
          emoji: "⚾",
          category: "orange",
          notes: "Wrigleyville",
          address: "Sluggers World Class Sports Bar, 3540 N Clark St, Chicago, IL",
          completed: false,
        },
        {
          id: "sun-8",
          time: "17:00",
          title: "Sluggers (cont.)",
          emoji: "⚾",
          category: "orange",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "sun-9",
          time: "18:00",
          title: "Nutella Café",
          emoji: "🍫",
          category: "orange",
          notes: "Pre-dinner sweet stop",
          address: "Nutella Café, 189 N Michigan Ave, Chicago, IL",
          completed: false,
        },
        {
          id: "sun-10",
          time: "19:00",
          title: "Dinner — Johjto Sushi",
          emoji: "🍣",
          category: "confirmed",
          notes: "",
          address: "Johjto Sushi, Chicago, IL",
          completed: false,
        },
        {
          id: "sun-11",
          time: "20:00",
          title: "Johjto Sushi (cont.)",
          emoji: "🍣",
          category: "confirmed",
          notes: "",
          address: "",
          completed: false,
        },
      ],
    },
    {
      id: "mon-apr-20",
      date: "2026-04-20",
      label: "Mon 4/20",
      labelFull: "Monday, April 20",
      activities: [
        {
          id: "mon-1",
          time: "09:00",
          title: "Breakfast",
          emoji: "☕",
          category: "free",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "mon-2",
          time: "10:00",
          title: "Pack Up / Check Out",
          emoji: "🧳",
          category: "travel",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "mon-3",
          time: "11:00",
          title: "Chicago Riverwalk + Vintage Newspaper Photo",
          emoji: "🚶",
          category: "orange",
          notes: "Michigan Ave near Tribune Tower — donation-based photo vendor",
          address: "Chicago Riverwalk, Chicago, IL",
          completed: false,
        },
        {
          id: "mon-4",
          time: "12:00",
          title: "Riverwalk / Newspaper Photo (cont.)",
          emoji: "🚶",
          category: "orange",
          notes: "",
          address: "",
          completed: false,
        },
        {
          id: "mon-5",
          time: "13:00",
          title: "Head to O'Hare",
          emoji: "🚗",
          category: "travel",
          notes: "Leave by 12:30 PM",
          address: "O'Hare International Airport, Chicago, IL",
          completed: false,
        },
        {
          id: "mon-6",
          time: "14:30",
          title: "Depart → LAX (~7 PM arrival)",
          emoji: "✈️",
          category: "travel",
          notes: "",
          address: "",
          completed: false,
        },
      ],
    },
  ],

  // Overflow / "If Time Permits" list
  overflow: [
    {
      id: "overflow-1",
      title: "Chinatown",
      emoji: "🏘️",
      notes: "Best as a half-day — needs dedicated time, hard to fit current schedule",
    },
    {
      id: "overflow-2",
      title: "Margie's Candies",
      emoji: "🍬",
      notes: "Old-school ice cream in Bucktown — quick detour if energy allows Saturday",
    },
  ],
};

export default chicagoItinerary;
